УРОК 3

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

In [1]:
import numpy as np

def wh_matrix(A,B):
    
    print(f'Матрица A\n{A}')
    print(f'Матрица B\n{B}')
    C = np.dot(A, B)
    print(f'Размерность матрицы произведения\n{len(C)}x{len(C[0])}')
    
    
def matrix_gen(str_m,clm_m):
    
   return np.random.sample((str_m, clm_m))
        
    

а)  A  — матрица  4×2 ,  B  — матрица  4×2

Произведения матриц AB И BC не определены

In [2]:
A = matrix_gen(4,2)
B = matrix_gen(4,2)
wh_matrix(A,B)

Матрица A
[[0.48924432 0.96502539]
 [0.20527519 0.34290887]
 [0.68459154 0.69639742]
 [0.63700275 0.04991007]]
Матрица B
[[0.47120783 0.06320643]
 [0.90900922 0.51893815]
 [0.8533481  0.9586965 ]
 [0.7080884  0.16388028]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [3]:
wh_matrix(B,A)

Матрица A
[[0.47120783 0.06320643]
 [0.90900922 0.51893815]
 [0.8533481  0.9586965 ]
 [0.7080884  0.16388028]]
Матрица B
[[0.48924432 0.96502539]
 [0.20527519 0.34290887]
 [0.68459154 0.69639742]
 [0.63700275 0.04991007]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

б) A — матрица 2×5 , B — матрица 5×3

AB - определено 2х3
BA - неопределено

In [4]:
A = matrix_gen(2,5)
B = matrix_gen(5,3)
wh_matrix(A,B)

Матрица A
[[0.08385054 0.56021196 0.5245457  0.82484239 0.87120572]
 [0.12464403 0.15823072 0.88411476 0.63452013 0.79051273]]
Матрица B
[[0.16421449 0.88066502 0.93473583]
 [0.33247637 0.54989519 0.29506991]
 [0.6480556  0.1006159  0.72861958]
 [0.26313321 0.67361291 0.22975802]
 [0.92881717 0.46662373 0.95213186]]
Размерность матрицы произведения
2x3


In [5]:
wh_matrix(B,A)

Матрица A
[[0.16421449 0.88066502 0.93473583]
 [0.33247637 0.54989519 0.29506991]
 [0.6480556  0.1006159  0.72861958]
 [0.26313321 0.67361291 0.22975802]
 [0.92881717 0.46662373 0.95213186]]
Матрица B
[[0.08385054 0.56021196 0.5245457  0.82484239 0.87120572]
 [0.12464403 0.15823072 0.88411476 0.63452013 0.79051273]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

в) A — матрица 8×3 , B — матрица 3×8

AB - определено 8х8
BA - определено 3х3

In [6]:
A = matrix_gen(8,3)
B = matrix_gen(3,8)
wh_matrix(A,B)

Матрица A
[[0.90110847 0.82655158 0.4338827 ]
 [0.64569435 0.74626502 0.86789536]
 [0.03568794 0.19624483 0.24678749]
 [0.88324525 0.77247153 0.41460226]
 [0.72448844 0.84149473 0.58311397]
 [0.11905403 0.95104599 0.29541507]
 [0.84425451 0.77774964 0.19388216]
 [0.04058946 0.55364297 0.92633408]]
Матрица B
[[0.88825022 0.11416881 0.4692661  0.68321624 0.04134634 0.60324522
  0.56819422 0.57915966]
 [0.04814829 0.71199765 0.07417085 0.65184013 0.85108477 0.84705013
  0.63782257 0.58046821]
 [0.28690227 0.85805103 0.46701434 0.20741372 0.05878692 0.02843071
  0.43310947 0.37954833]]
Размерность матрицы произведения
8x8


In [7]:
wh_matrix(B,A)

Матрица A
[[0.88825022 0.11416881 0.4692661  0.68321624 0.04134634 0.60324522
  0.56819422 0.57915966]
 [0.04814829 0.71199765 0.07417085 0.65184013 0.85108477 0.84705013
  0.63782257 0.58046821]
 [0.28690227 0.85805103 0.46701434 0.20741372 0.05878692 0.02843071
  0.43310947 0.37954833]]
Матрица B
[[0.90110847 0.82655158 0.4338827 ]
 [0.64569435 0.74626502 0.86789536]
 [0.03568794 0.19624483 0.24678749]
 [0.88324525 0.77247153 0.41460226]
 [0.72448844 0.84149473 0.58311397]
 [0.11905403 0.95104599 0.29541507]
 [0.84425451 0.77774964 0.19388216]
 [0.04058946 0.55364297 0.92633408]]
Размерность матрицы произведения
3x3


г) A — квадратная матрица 4×4 , B — квадратная матрица 4×4

AB и BA - определено 4х4

In [8]:
A = matrix_gen(4,4)
B = matrix_gen(4,4)
wh_matrix(A,B)

Матрица A
[[0.32217754 0.5628743  0.48189009 0.92949602]
 [0.04342645 0.03590307 0.71261648 0.09517509]
 [0.71538201 0.1778402  0.31331676 0.35620813]
 [0.32500883 0.10199839 0.64016012 0.02234734]]
Матрица B
[[0.54145947 0.6548791  0.64183225 0.73432609]
 [0.36169895 0.05422341 0.26797959 0.94924948]
 [0.25900338 0.87584118 0.2544345  0.3425731 ]
 [0.31458543 0.2920809  0.4874462  0.04055252]]
Размерность матрицы произведения
4x4


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A * B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1*4 + 0*(-2) & -1*1 - 2*5\\ 
3*4 + 0*0 & -1*3 + 0*5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [9]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

A+B

array([[ 5, -3],
       [ 3,  5]])

In [10]:
np.dot(A,B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3*\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2*\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$ = $\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}-\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$=$\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [11]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$At=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$.

$AA^{T}$ = $\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}*\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$ = $\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^{T}A$ = $\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}*\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$ = $\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$


In [12]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.transpose()

np.dot(A,At)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [13]:
np.dot(At,A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

НЕ УСПЕЛ ДОДЕЛАТЬ. ПОКА НЕ ПРАВИЛЬНО РАБОТАЕТ!

In [30]:
def matrix_dot(A,B):
    
    if len(A[0]) != len(B):
        return 'матрицы не определены'
    
    AB = []
    temp=[]
    s=0     
    
    r1=len(A)
    c1=len(A[0])   
    r2=c1         
    c2=len(B[0])
        
    for z in range(0,r1):
        for j in range(0,c2):
            for i in range(0,c1):
                s=s+A[z][i]*B[i][j]
                temp.append(s)
                s=0
            AB.append(temp)
            temp=[]
            
    return AB
    

In [31]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

matrix_dot(A,B)

[[4, 0], [-1, -10], [12, 0], [-3, 0]]

In [16]:
np.dot(A,B)

array([[  4, -11],
       [ 12,  -3]])

УРОК 4

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$detA = sin^2x + cos^2x = 1$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$detA = 4*5*9 + 2*1*0 + 3*0*0 + 0*5*3 - 0*1*4 - 9*0*2 = 180$

In [17]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$detA = 1*5*9 + 2*6*7 + 3*4*8 - 7*5*3 - 8*6*1 - 9*4*2 = 45 + 84 + 96 - 105 - 48 - 72 = 0$

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

In [19]:
A = np.array([[2, 0], [-5, 2]])
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Определитель:
4


а) $det(A^{2})$

$$det(A^{2}) = det(A) * det(A) = 4*4 = 16$$

In [20]:
print(f'Определитель:\n{np.linalg.det(np.dot(A,A)):.0f}')

Определитель:
16


 б) $det(A^{T})$
 
 Определитель транспонированной матрицы равен определителю исходной:
    $$detA^{T}=detA=4$$

In [21]:
print(f'Определитель:\n{np.linalg.det(A.transpose()):.0f}')

Определитель:
4


 в) $det(2A)$
 
 $$det(λA)=λ^r*detA$$
 где r - ранг матрицы
 $$det(2A)=2^2*detA = 16$$

In [22]:
A2 = 2*A
print(f'Определитель:\n{np.linalg.det(A2):.0f}')

Определитель:
16


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

Для доказательства вырожденности, найдем определитель, если он равен 0, тогда матрица вырождена (сингулярна)
$$detA = (-2)*(-14)*13 + 7*6*(-3) + (-3)*4*13 - (-3)*(-14)*(-3) - 7*6*(-2) - 13*4*7 = 0$$

In [23]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Определитель:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

так как третья строка равна сумме первых двух, ранг матрицы 2

In [26]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы:\n{np.linalg.matrix_rank(A)}')

Ранг матрицы:
2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

так как третья строка равна сумме первых двух, ранг матрицы 3


In [27]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Ранг матрицы:\n{np.linalg.matrix_rank(A)}')

Ранг матрицы:
3
