__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

собственные значения:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix} = \lambda 
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$$

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix}=0,$$

$$(-1-\lambda)(6-\lambda) + 12=0$$

$$\lambda^{2}-5\lambda+6=0$$

Собственные значение: $\lambda_{1}=2, \lambda_{2}=3$

При $\lambda=2$:

$$\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
 2x_{1}+6x_{2}= 2x_{2}.
\end{cases}$$

$$x_{1} = -2x_{2}$$

Первый собственный вектор $(с,-2с)$ где с - любое число 

При $\lambda=3$:

$$\begin{cases}
-x_{1}-6x_{2}= 3x_{1}, \\
 2x_{1}+6x_{2}= 3x_{2}.
\end{cases}$$

$$x_{1} = -1.5x_{2}$$

Первый собственный вектор $(с,-1.5с)$ где с - любое число 


In [2]:
import numpy as np

a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}=\begin{pmatrix}
-cos(0) & sin(0)\\ 
sin(0) & -cos(0)
\end{pmatrix}$$

При повороте на 180 градусов:

$$\begin{pmatrix}
-cos(180) & sin(180)\\ 
sin(180) & -cos(180)
\end{pmatrix}=\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix}$$

Данная матрица является единичной $\Rightarrow$
$$\lambda_{1}=\lambda_{2}=1$$

При поиске собственных векторов, оказывается, что у нас умножается матрица из нулей на собственный вектор и в итоге получается нулевой столбец $\Rightarrow$ собственный вектор может быть любым

In [3]:
a = np.array([[1, 0], [0, 1]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[1 0]
 [0 1]]
Собственные значения:
[1. 1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
1+1=\lambda \\ 
-1+3 = \lambda
\end{cases}
\Rightarrow
\lambda=2.$$

Так как мы нашли единственное значение $\lambda$ $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$.

**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора. Аналогично методике из предыдущего примера получим:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
\Rightarrow
\lambda=3\pm i.$$

Таким образом, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, в геометрическом смысле: ни один ненулевой вектор после поворота на 30 градусов не отобразится в коллинеарный исходному.